# docker-compose.prod.yml - Production (Build)
name: dataviz-prod

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.python
      args:
        APP_USERNAME: "${APP_USERNAME}"
        DATA_PATH: "${DATA_PATH}"
        APP_PATH: "${APP_PATH}"
        UPLOAD_DIR: "${UPLOAD_DIR}"
    container_name: python-backend.bd
    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"
    volumes:
      - ./data:/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "${VUE_APP_API_BASE_URL}${API_BASE_URL}/health"]
      interval: 3s
      timeout: 5s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.75'
    user: ${APP_USERNAME}:${APP_USERNAME}
    security_opt:
      - no-new-privileges:true
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.vue
      args:
        NODE_ENV: "${NODE_ENV}"
        HOST: "${HOST}"
        BASE_URL: "${VUE_APP_BASE_URL}"
        VUE_PORT: "${VUE_PORT}"
        APP_PATH: "${APP_PATH}"
    container_name: vue-frontend.bd
    ports:
      - "${VUE_PORT}:8080"
#    volumes:
#      - ./frontend:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "${VUE_APP_BASE_URL}:{VUE_PORT}"]
      interval: 3s
      timeout: 5s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
    networks:
      - app-network
    env_file:
      - .env
    environment:
      - HOST=${HOST}
    depends_on:
      backend:
        condition: service_healthy

networks:
  app-network:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450