FROM python:3.9-slim

# Create a working directory
WORKDIR /app

# Copy application and data files
COPY ./app /app/app
COPY ./data /app/data

# Copy requirements file and install dependencies
COPY requirements.txt /app
RUN pip install --no-cache-dir -r requirements.txt

# Expose the backend port
EXPOSE 5001

# Command to run the app using Gunicorn
CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:5001", "api.api:app"]
