# docker-compose.yml - Development
name: dataviz-dev

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.python
      args:
        NODE_ENV: "${NODE_ENV}"
    container_name: python-backend-dev
    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"
    volumes:
      - ./data:/data
      - ./app:/app  # Keep for development hot-reloading
    env_file:
      - .env.dev
    healthcheck:
      test: ["CMD", "curl", "-f", "${VUE_APP_API_BASE_URL}${API_BASE_URL}/health"]
      interval: 5s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.75'
    user: ${APP_USERNAME:-sunburst}
    security_opt:
      - no-new-privileges:true
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.vue
      args:
        NODE_ENV: "${NODE_ENV}"
    container_name: vue-frontend-dev
    ports:
      - "${VUE_PORT}:${VUE_PORT}"
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Keep for development dependencies
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${VUE_PORT}"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
    networks:
      - app-network
    env_file:
      - .env.dev
    environment:
      - HOST=0.0.0.0
    command: npm run serve
    depends_on:
      backend:
        condition: service_healthy

networks:
  app-network:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450