name: dataviz

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
      args:
        REQUIREMENTS_FILE: backend/requirements.txt
    env_file:
      - .env.dev
    ports:
      - "${BACKEND_PORT:-6500}:${BACKEND_PORT:-6500}"
    volumes:
      - ./backend/data:/app/data
    environment:
      - FLASK_ENV=production
      - HOST=0.0.0.0
      - FLASK_PORT=${BACKEND_PORT:-6500}
    restart: always

  frontend:
    build:
      context: ./frontend
    env_file:
      - .env.dev
    ports:
      - "${FRONTEND_PORT:-3000}:80"
    depends_on:
      - backend
    restart: always
