# docker-compose.prod.yml - Production
name: dataviz-prod
env_file: .env.prod

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.python
    environment:
      - FLASK_ENV=production
      - API_BASE_URL=/dataviz/api
    env_file:
      - .env.prod
    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"
    volumes:
      - ./data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${FLASK_PORT}${API_BASE_URL}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    restart: always
    security_opt:
      - no-new-privileges:true
    user: ${APP_USERNAME:-sunburst}

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.vue
      args:
        - NODE_ENV=production
        - VUE_APP_API_BASE_URL=${VUE_APP_API_BASE_URL}
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${VUE_PORT}"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    restart: always
    depends_on:
      backend:
        condition: service_healthy

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450  # Optimized for most cloud providers